/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseLogo: typeof import('./src/components/ui/logo/BaseLogo.vue')['default']
    Button: typeof import('primevue/button')['default']
    Image: typeof import('primevue/image')['default']
    PhaserGame: typeof import('./src/components/PhaserGame/PhaserGame.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
